
version: "2.4"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto.bit.lan
    restart: unless-stopped

    mem_limit: 512M

    network_mode: host

    #ports:
    #  - "1883:1883"
    #  - "9001:9001"

    volumes:
      - ./config:/mosquitto/config/
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log

    labels:
      - com.centurylinklabs.watchtower.enable=true
