
version: "2.4"

name: grafana-example-com

services:
  grafana:
    image: grafana/grafana:latest-ubuntu

    container_name: grafana.example.com
    
    restart: always

    user: www-data
    
    volumes:
      - ./conf:/etc/grafana
      - ./data:/var/lib/grafana

    ports:
      - 3000:3000

    labels:
      - com.centurylinklabs.watchtower.enable=true

