# Filename: docker-compose.yml

version: "3.7"

name: nodered-example-com

services: 
  node-red:
    image: nodered/node-red:latest

    container_name: nodered.example.com

    ports:
      - "1880:1880"

    environment:
      - TZ=Asia/Kolkata

    volumes:
      - "./node-red-data:/data"

    labels:
      - com.centurylinklabs.watchtower.enable=true